name: Deploying app to Netlify
# 뜻! master branch 에서 push 할때만 deploy.yaml 이 실행되도록.
on:
  push:
    branches:
    - master

jobs:
  my-deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.18]

    steps:
      - name: Checking out repository code
        uses: actions/checkout@v2 # git clone 하는 action 예를 들어서 npm 에서 install 하는거랑 비슷

      - name: Use Node.js ${{ matrix.node-version }}
          # npm install / 패키지이름 github action에서 사용하기 때문에 actions/ 
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Building react app
        run: |
          npm install -g yarn
          yarn
          yarn build

      - name: Publishing
        run: |
          npm install netlify-cli -g
          netlify deploy --dir=./build --prod --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}