name: Build docker image and publish on docker hub

on: workflow_dispatch

jobs:
  docker-build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v2

        # https://github.com/marketplace/actions/build-and-push-docker-images 그대로 복붙하면됨
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setting environment variables
        run: |
          chmod +x ./scripts/set-env.sh
          ./scripts/set-env.sh

        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          REACT_APP_API_BASE: ${{secrets.REACT_APP_API_BASE}} # EC2 의 Public IPv4 DNS 값이다. 
      - name: Building docker image
        run: make build

      - name: Publishing docker image
        run: make push